server:
  port: 3000
  host: localhost
auth:
  token: ''
proxy:
  enabled: true
  host: 127.0.0.1
  port: 10808
  protocol: socks5
cloudflare:
  apiToken: null
  zoneId: null
  emailForward: null
  virtualDomain: null
  proxy: false
email:
  proxy: true
  type: publicApi
  publicApi:
    apiEndpoint: https://emailapi.goaiwork.online
  user: null
  pass: null
  tempmail:
    preferredDomain: fexpost.com
    customizeUsername: true
    username: null
    pin: null
    lifetime: 2days
  smtp:
    host: smtp.gmail.com
    port: 465
    secure: true
    enabled: false
  imap:
    enabled: true
    host: imap.gmail.com
    port: 993
    secure: true
logging:
  level: info
  path: logs
  maxSize: 10m
  maxFiles: 5
registration:
  type: cursor
  manual: false
browser:
  proxy: true
  headless: false
  checkFingerprint: false
